name: Deploy Frontend to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH with Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # 🔥 Using password authentication
          script: |
            cd /var/www/html/facial_recognition/frontend
            git pull origin main
            npm install
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
